myTuple = (1,2,3,"Jameel",1,1,5)
print(type(myTuple))
print(myTuple)
emptyTuple = ()
print(type(emptyTuple))
singleTuple=(1)
print(type(singleTuple))
singleRealTuple=("Nouman",)
print(type(singleRealTuple))
# myTuple[2]= "January"
# print(myTuple)
print(len(myTuple))
print(myTuple.index(2))
print(myTuple.count(1))
print(myTuple.count("Nanga"))